# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3006d4560bedcac226f793d58ac7efae7b2187d97273381d41bd748307848fdea6dca10e99bf270e93130cce8aa8eead472017bc0090d02356c9fb771c8b6d30

test:
  secret_key_base: ca9d0bfdbc7664761c66dbc1fed14c913edb2703ff77b610f2647864912f3c359cb102fe1abdc50e694fd46c6574e6a94bada5121c4e276c36aab5acdb361bf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
# i.e. secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: example